# Basic Information 
title: Nicolas Girard
position: Ph.D. Student
affiliation: Mines Paris - PSL
affiliation_link: https://www.minesparis.psl.eu/
affiliation_logo: ./assets/img/logo_mines.svg
email: nicolas.girard1@minesparis.psl.eu

# Search Engine Optimization (SEO)
keywords: nicolas girard, girard nicolas, nicolasgirard, girardnicolas
canonical: https://nicolas-girard.github.io/
description: Nicolas Girard is a Ph.D. Student at Mines Paris - PSL. His research lies in statistical seismology, fault mechanism and seismic hazard.

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
cv_link: ./assets/files/curriculum_vitae.pdf
github_link: https://github.com/nicolas-girard/
linkedin: https://www.linkedin.com/in/n-girard/

# Images 
avatar: ./assets/img/avatar.jpg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnotes
# footnote: Feel free to use my website's source code.
# " footnote_link: https://github.com/yaoyao-liu/minimal-light

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
# font: "Serif" # or "Sans Serif"

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
# clustrmaps_id: CJD8XwsJhSyQ6sbsU-Gw0cNcUlbah7KW3xvHN2QlwW0

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
